import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

async function api(path:string, options:any={}) {
  const response=await fetch('/api'+path,{...options,headers:options.body instanceof FormData?{}:{'Content-Type':'application/json',...options.headers}});
  const data=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||response.status));
  return data;
}
const send=(path:string,body:any={})=>api(path,{method:'POST',body:JSON.stringify(body)});
const labels:any={draft:'Черновик',processing:'Обработка',ready_for_review:'Проверка',confirmed:'Подтверждён',queued:'В очереди',running:'Выполняется',succeeded:'Готово',failed:'Ошибка',canceled:'Отменено',extract:'Поручения',reconcile:'Объединение',summary:'Саммари',verify:'Проверка источников',qa:'Ответ на вопрос',index:'RAG-индекс',speech:'Речь и говорящие',export:'Экспорт'};
const example='Председатель: Айдана, подготовь отчёт к пятнице.\nАйдана: Да, подготовлю отчёт к пятнице.\nПредседатель: Ерлан должен обновить план безопасности. Срок пока не определён.\nБотагоз: По проекту выполнено 68 процентов работ.\nПредседатель: Итого: Айдана готовит отчёт, Ерлан обновляет план безопасности.';

function App(){
 const[user,setUser]=useState<any>(null),[boot,setBoot]=useState(true),[error,setError]=useState(''),[info,setInfo]=useState('');
 const[list,setList]=useState<any[]>([]),[selected,setSelected]=useState(''),[meeting,setMeeting]=useState<any>(null),[system,setSystem]=useState<any>({}),[notices,setNotices]=useState<any[]>([]);
 const[draft,setDraft]=useState<any[]>([]),[draftRevision,setDraftRevision]=useState(0),[text,setText]=useState(''),[question,setQuestion]=useState('');
 const[busy,setBusy]=useState(false),[showNew,setShowNew]=useState(false),audio=useRef<HTMLAudioElement>(null);
 useEffect(()=>{api('/me').then(setUser).catch(()=>{}).finally(()=>setBoot(false));},[]);
 async function refresh(){if(!user)return;const [ls,ns]=await Promise.all([api('/meetings'),api('/notifications')]);setList(ls);setNotices(ns);if(selected){const m=await api('/meetings/'+selected);setMeeting(m);setDraftRevision(old=>{if(old!==m.revision){setDraft(structuredClone(m.document.actions||[]));}return m.revision;});}}
 useEffect(()=>{if(!user)return;refresh().catch(e=>setError(e.message));api('/system').then(setSystem).catch(()=>{});const t=setInterval(()=>refresh().catch(()=>{}),2500);return()=>clearInterval(t);},[user,selected]);
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');setInfo('');try{await fn();await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function source(id:string){const s=meeting?.document.segments.find((x:any)=>x.id===id);if(s&&audio.current){audio.current.currentTime=s.start_ms/1000;audio.current.play().catch(()=>{});}document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'center'});}
 if(boot)return <main className="login"><p>Загрузка…</p></main>;
 if(!user)return <main className="login"><div className="brand">HA <span>MEETINGS / LOCAL</span></div><h1>Совещание заканчивается.<br/>Решения остаются.</h1><p>Локальный помощник: запись, поручения и протокол с проверяемыми источниками.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await send('/login',Object.fromEntries(f));setUser(await api('/me'));});}}><label>Email<input name="email" type="email" defaultValue="admin@local.test" required/></label><label>Пароль<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>Войти</button>{error&&<p role="alert" className="error">{error}</p>}<small>Учётные данные приложения находятся в локальном .env: ADMIN_EMAIL и ADMIN_PASSWORD.</small></form></main>;
 return <div className="shell"><aside><div className="brand">HA <span>MEETINGS / LOCAL</span></div><button onClick={()=>setShowNew(!showNew)}>+ Новое совещание</button><div className="navlabel">СОВЕЩАНИЯ <span>{list.length}</span></div><nav>{list.map(m=><button className={'meeting-link '+(selected===m.id?'active':'')} key={m.id} onClick={()=>{setDraftRevision(0);setMeeting(null);setSelected(m.id);}}><strong>{m.title}</strong><span>{labels[m.state]}</span></button>)}</nav><footer><a href={`http://${location.hostname}:5678`} target="_blank" rel="noreferrer">Открыть схемы n8n ↗</a><small>{user.email}</small><button className="quiet" onClick={()=>run(async()=>{await send('/logout');setUser(null);})}>Выйти</button></footer></aside><main>
 <header><div><span className="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</span><h1>Протоколы и поручения</h1></div><div className="status"><i className={system.ollama?.ready?'green':''}/>{system.ollama?.ready?'Ollama доступен':'Проверка Ollama'}<small>{system.llm_model||'локальная модель'}</small></div></header>
 {error&&<div role="alert" className="error banner">{error}</div>}{info&&<div className="banner">{info}</div>}
 {showNew&&<section className="card"><h2>Новое совещание</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const m=await send('/meetings',{title:f.get('title'),started_at:f.get('date')||null,timezone:'Asia/Qyzylorda',participants:String(f.get('participants')).split(',').map(x=>x.trim()).filter(Boolean),consent:f.get('consent')==='on'});setSelected(m.id);setShowNew(false);});}}><div className="columns"><label>Тема<input name="title" required placeholder="Планирование проекта"/></label><label>Дата и время · Asia/Qyzylorda<input name="date" type="datetime-local"/></label></div><label>Участники через запятую<input name="participants" placeholder="Айдана, Ерлан, Ботагоз"/></label><label className="check"><input type="checkbox" name="consent" required/>Участники уведомлены о записи и обработке; у меня есть право загрузить эти данные.</label><button disabled={busy}>Создать</button></form></section>}
 {!meeting&&!selected&&<section className="welcome card"><span className="eyebrow">ОТ РЕЧИ К РЕШЕНИЯМ</span><h2>Загрузите запись.<br/>Проверьте, что поручено.</h2><p>Помощник выделит говорящих, найдёт поручения и подготовит черновик. Вы проверяете исполнителей и сроки, затем подтверждаете документ.</p><div className="steps"><span>01 / Запись</span><span>02 / Анализ</span><span>03 / Проверка</span><span>04 / Протокол</span></div><button onClick={()=>setShowNew(true)}>Начать совещание</button></section>}
 {meeting&&<><div className="meeting-title"><h2>{meeting.title}</h2><span className="pill">{labels[meeting.state]} · версия {meeting.revision}</span></div>
 <section className="card"><h3>Источник</h3><div className="columns"><div><label>Аудио или видео<input type="file" accept="audio/*,video/*" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{const data=new FormData();data.append('file',file);await api(`/meetings/${selected}/media`,{method:'POST',body:data});setInfo('Запись загружена. Обработка идёт локально.');});}}/></label><small>До 500 МБ. RU / KZ / смешанная речь. Разметку голосов необходимо проверить.</small>{meeting.document.media_filename&&<audio ref={audio} controls src={`/api/meetings/${selected}/audio`}/>}</div><details><summary>Вставить готовый транскрипт</summary><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Имя: реплика" rows={6}/><div className="actions"><button className="quiet" onClick={()=>setText(example)}>Вымышленный пример</button><button disabled={busy||!text.trim()} onClick={()=>run(async()=>{await send(`/meetings/${selected}/transcript`,{text,expected_revision:meeting.revision});setInfo('Анализ поставлен в очередь n8n.');})}>Анализировать</button></div></details></div></section>
 <section className="card"><h3>Ход обработки</h3><div className="job-list">{meeting.jobs.length?meeting.jobs.map((j:any)=><div key={j.id} className={'job '+j.state}><strong>{labels[j.kind]||j.kind}</strong><span>{labels[j.state]}{j.tool_calls?` · tools: ${j.tool_calls}`:''}</span>{j.error&&<small>{j.error}</small>}</div>):<p>Добавьте запись или транскрипт.</p>}</div></section>
 {meeting.document.segments?.some((s:any)=>s.timing_source==='asr')&&<section className="card"><h3>Кто говорит</h3><p>Прослушайте реплики и выберите имена из списка участников. После сохранения анализ будет выполнен заново.</p>{meeting.document.participants?.length?<form key={`${selected}-${meeting.revision}`} onSubmit={e=>{e.preventDefault();const mapping=Object.fromEntries([...new FormData(e.currentTarget)].filter(([,value])=>value));run(async()=>{await send(`/meetings/${selected}/speaker-map`,{mapping,expected_revision:meeting.revision});setInfo('Имена сохранены. Начат анализ с подтверждёнными говорящими.');});}}><div className="columns">{[...new Set<string>(meeting.document.segments.map((s:any)=>s.speaker_id||s.speaker))].map(id=>{const segment=meeting.document.segments.find((s:any)=>(s.speaker_id||s.speaker)===id);return <label key={id}>{id}<select name={id} defaultValue={segment.speaker_confirmed?segment.speaker:''}><option value="">Не определён</option>{meeting.document.participants.map((name:string)=><option key={name} value={name}>{name}</option>)}</select></label>;})}</div><button disabled={busy}>Сохранить говорящих и повторить анализ</button></form>:<p>Имена можно сопоставить, если участники указаны при создании совещания.</p>}</section>}
 {(meeting.document.summary?.length>0)&&<section className="card"><h3>Краткое саммари</h3>{meeting.document.summary.map((s:any,i:number)=><p key={i}>{s.text} <button className="citation" onClick={()=>source(s.source_segment_ids[0])}>Источник ↗</button></p>)}</section>}
 {(meeting.state==='ready_for_review'||meeting.state==='confirmed')&&<section className="card"><div className="section-head"><h3>Поручения <span className="count">{draft.length}</span></h3><small>Проверьте исполнителей и даты перед подтверждением.</small></div><div className="table-wrap"><table><thead><tr><th>Что сделать</th><th>Исполнитель</th><th>Срок</th><th>Статус</th><th>Источник</th></tr></thead><tbody>{draft.map((a:any,i:number)=><tr key={a.id}><td><textarea value={a.title} onChange={e=>setDraft(draft.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></td><td><input value={a.assignee_mention||''} placeholder="Не определён" onChange={e=>setDraft(draft.map((x,j)=>j===i?{...x,assignee_mention:e.target.value||null}:x))}/></td><td><input type="date" value={a.due?.date||''} onChange={e=>setDraft(draft.map((x,j)=>j===i?{...x,due:{...x.due,date:e.target.value||null}}:x))}/><small>{a.due_raw||'Срок не указан'}</small></td><td><select value={a.status} onChange={e=>setDraft(draft.map((x,j)=>j===i?{...x,status:e.target.value}:x))}><option value="open">Открыто</option><option value="in_progress">В работе</option><option value="done">Готово</option></select></td><td><button className="citation" onClick={()=>source(a.source_segment_ids[0])}>Реплика ↗</button></td></tr>)}</tbody></table></div>{meeting.document.warnings?.map((w:string,i:number)=><p className="warning" key={i}>{w}</p>)}<div className="actions"><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await api(`/meetings/${selected}/review`,{method:'PUT',body:JSON.stringify({expected_revision:meeting.revision,actions:draft})});setInfo('Правки сохранены. Подтвердите новую ревизию.');})}>Сохранить правки</button><button disabled={busy||meeting.state==='confirmed'} onClick={()=>run(async()=>{const m=await api(`/meetings/${selected}/review`,{method:'PUT',body:JSON.stringify({expected_revision:meeting.revision,actions:draft})});await send(`/meetings/${selected}/confirm`,{expected_revision:m.revision});setInfo('Протокол подтверждён. Создаётся локальный RAG-индекс.');})}>Подтвердить протокол</button></div></section>}
 {meeting.state==='confirmed'&&<section className="card"><h3>Протокол и поиск по совещанию</h3><div className="actions">{['pdf','docx'].map(format=><button className="secondary" key={format} disabled={busy} onClick={()=>run(async()=>{await send(`/meetings/${selected}/exports`,{format});setInfo('Файл готовится; ссылка появится ниже.');})}>Создать {format.toUpperCase()}</button>)}{meeting.jobs.filter((j:any)=>j.kind==='export'&&j.state==='succeeded'&&j.revision===meeting.revision).map((j:any)=><a key={j.id} href={`/api/exports/${j.id}`} className="download">Скачать {j.result.format?.toUpperCase()} ↓</a>)}</div><form className="question" onSubmit={e=>{e.preventDefault();run(async()=>{await send(`/meetings/${selected}/questions`,{question});setQuestion('');});}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder={meeting.indexed_revision===meeting.revision?'Кто готовит отчёт и к какому сроку?':'Индекс создаётся…'} required/><button disabled={busy||meeting.indexed_revision!==meeting.revision}>Спросить</button></form>{meeting.jobs.filter((j:any)=>j.kind==='qa'&&j.state==='succeeded'&&j.revision===meeting.revision).map((j:any)=><div className="answer" key={j.id}><p>{j.result.answer}</p>{j.result.source_segment_ids?.map((id:string)=><button className="citation" key={id} onClick={()=>source(id)}>Источник ↗</button>)}</div>)}</section>}
 <section className="card"><h3>Реплики <span className="count">{meeting.document.segments?.length||0}</span></h3><div className="transcript">{meeting.document.segments?.map((s:any)=><div id={s.id} className="segment" key={s.id}><button onClick={()=>source(s.id)}>{s.timing_source==='manual'?'Текст':new Date(s.start_ms).toISOString().slice(14,19)}</button><div><strong>{s.speaker}</strong><p>{s.text}</p></div></div>)}</div></section>
 <button className="danger quiet" disabled={busy} onClick={()=>{if(confirm('Удалить совещание, запись и производные данные?'))run(async()=>{await api('/meetings/'+selected,{method:'DELETE'});setSelected('');setMeeting(null);});}}>Удалить совещание</button></>}
 <details className="card"><summary>Справочник для RAG</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await send('/references',Object.fromEntries(f));setInfo('Справочник принят для локального индексирования.');});}}><label>Название<input name="title" required/></label><label>Утверждённый текст<textarea name="text" rows={4} required/></label><button disabled={busy}>Добавить справочник</button></form></details>
 {notices.length>0&&<section className="card"><h3>Напоминания</h3>{notices.map(n=><p key={n.id}>{n.text}</p>)}</section>}
 <p className="footnote">Локальные модели · подтверждение человеком · источники у каждого решения</p>
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
